# Generated by Django 5.0.14 on 2025-06-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('idMonth', models.UUIDField(db_column='idMonth', primary_key=True, serialize=False)),
                ('month', models.CharField(db_column='month', max_length=50)),
            ],
            options={
                'db_table': 'Month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypePayment',
            fields=[
                ('idPayment', models.UUIDField(db_column='idPayment', primary_key=True, serialize=False)),
                ('namePayment', models.CharField(db_column='namePayment', max_length=50)),
            ],
            options={
                'db_table': 'TypePayment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='vEmployeeAutorizado',
            fields=[
                ('idEmployee', models.UUIDField(db_column='idEmployee', primary_key=True, serialize=False)),
                ('idArea', models.UUIDField(db_column='idArea')),
                ('emailBusiness', models.CharField(db_column='emailBusiness', max_length=100)),
            ],
            options={
                'db_table': 'v_EmployeeAutorizado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='vPayRollAutorizado',
            fields=[
                ('idPayRoll', models.UUIDField(db_column='idPayRoll', primary_key=True, serialize=False)),
                ('idUser', models.UUIDField(db_column='idUser')),
                ('idMonth', models.UUIDField(db_column='idMonth')),
                ('idPayment', models.UUIDField(db_column='idPayment')),
                ('totalValue', models.DecimalField(db_column='totalValue', decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'v_PayRollAutorizado',
                'managed': False,
            },
        ),
    ]
